name: CI → Test, Build & Push

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none
          tools: composer

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Lint (PHPCS)
        run: vendor/bin/phpcs --standard=PSR12 src

      - name: Static analysis (PHPStan)
        run: vendor/bin/phpstan analyse src --no-progress --memory-limit=1G

      - name: Unit tests (PHPUnit)
        run: vendor/bin/phpunit --configuration phpunit.xml --testdox

  build-and-push:
    # Only build & push on repo pushes (not PRs)
    if: github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write   # needed to create/push the build-* tag
      packages: write   # needed to push to GHCR
    env:
      # Start with canonical image name and force lowercase (GHCR requirement)
      IMAGE_NAME: ghcr.io/${{ github.repository }}
    steps:
      - uses: actions/checkout@v4

      - name: Force image name to lowercase
        run: echo "IMAGE_NAME=${IMAGE_NAME,,}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # Push :latest on pushes to main
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/heads/main') }}
            # Push :vX.Y.Z when the ref is a tag like v1.2.3
            type=semver,pattern={{version}}
            # Always add a SHA tag for traceability
            type=sha,format=short

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Tag commit with build number (only on main branch)
        if: github.ref == 'refs/heads/main'
        env:
          TAG: build-${{ github.run_number }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag "$TAG"
          git push origin "$TAG"
